repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff Check
        entry: nox -s ruff-check
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

      - id: ruff-format-check
        name: Ruff Format Check
        entry: nox -s ruff-format-check
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

      - id: mypy
        name: MyPy Type Check
        entry: nox -s mypy
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

      - id: security
        name: Security Check (Bandit)
        entry: nox -s security
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

      - id: test
        name: Run Tests
        entry: nox -s test
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
        stages: [pre-push]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict