services:
  db:
    image: postgres:15.4-alpine
    container_name: slavbor_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

  test_db:
    image: postgres:15.4-alpine
    container_name: slavbor_test_db
    environment:
      POSTGRES_USER: slavbor_user
      POSTGRES_PASSWORD: test_secret
      POSTGRES_DB: slavbor_test_db
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4:7.6
    container_name: slavbor_pgadmin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app_network

  redis:
    image: redis:7.2.3-alpine
    container_name: slavbor_redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  test_redis:
    image: redis:7.2.3-alpine
    container_name: slavbor_test_redis
    ports:
      - "6381:6379"
    volumes:
      - test_redis_data:/data
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slavbor_fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - test_db
      - redis
      - test_redis
    volumes:
      - .:/app
    networks:
      - app_network

volumes:
  postgres_data:
  test_postgres_data:
  pgadmin_data:
  redis_data:
  test_redis_data:

networks:
  app_network:
    driver: bridge
