"""remove useless index

Revision ID: 3d6b77010d1b
Revises: 5fd1788d0331
Create Date: 2025-07-04 10:07:47.271374

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3d6b77010d1b"
down_revision: Union[str, None] = "5fd1788d0331"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("idx_ability_description_fts"),
        table_name="abilities",
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("idx_ability_description_fts"),
        "abilities",
        ["description"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###
