name: Check Source Branch
on:
  pull_request:
    branches: [main]
  pull_request_target:
    branches: [main]

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          SOURCE_BRANCH="${{ github.event.pull_request.head.ref }}"
          echo "Checking source branch: $SOURCE_BRANCH"
          
          if [ "$SOURCE_BRANCH" != "development" ]; then
            echo "❌ Pull requests to main must come from 'dev' branch only"
            echo "Current source: $SOURCE_BRANCH"
            exit 1
          fi
          
          echo "✅ Source branch check passed"